services:
  postgres:
    image: postgres:16-alpine
    container_name: skillquest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: skillquest
      POSTGRES_PASSWORD: skillquest_password
      POSTGRES_DB: skillquest_db
    ports:
      - "5432:5432"
    volumes:
      - skillquest_postgres_data:/var/lib/postgresql/data

volumes:
  skillquest_postgres_data: